### ISSUE TITLE
Modifier le message de compatibilité

### ISSUE THREAD

**Issue by noftaly** [Uneo7/Skript-MC-Doc#10]
Dans les syntaxes des addons (côté utilisateur), il y a marqué que la syntaxe est compatible depuis skript xx, alors qu'il faudrait marquer qu'elle est compatible depuis la version XX de l'addon.

![image](https://user-images.githubusercontent.com/34779161/51260433-90737380-19ae-11e9-9157-52e786d08afc.png)
ca par exemple c'est la compatibilité d'une syntaxe de l'addon Sk-NBeeT

**Comment by Uneo7** [comment]
Réglé
