### ISSUE TITLE
Modifier les couleurs de la dépréciation

### ISSUE THREAD

**Issue by noftaly** [Uneo7/Skript-MC-Doc#11]
Personnellement, j'inverserai les couleurs de la compatibilité et de la dépréciation. Cad que en haut a droite, la compatibilité devrait être en bleu, et au milieu, la dépréciation en rouge

![capture d ecran 2019-01-16 a 16 51 18](https://user-images.githubusercontent.com/34779161/51260686-2909f380-19af-11e9-93a3-431e78d6ef22.png)

**Comment by Uneo7** [comment]
Changé
