### ISSUE TITLE
Ajouter du padding sous Exemple et Pattern

### ISSUE THREAD

**Issue by noftaly** [Uneo7/Skript-MC-Doc#12]
Faudrait ajouter un peu de marge sous Exemple et Pattern, comme il y a en dessous de Description...
![capture d ecran 2019-01-16 a 16 53 20](https://user-images.githubusercontent.com/34779161/51260798-55257480-19af-11e9-8be3-3536da57dfbc.png)
:)

**Comment by Uneo7** [comment]
Je connais ce bug, il sera fixé quand j'aurais fait la coloration syntaxique.

**Comment by Uneo7** [comment]
C'est bon
