### ISSUE TITLE
Corriger les fautes (homepage)

### ISSUE THREAD

**Issue by Angel-0** [Uneo7/Skript-MC-Doc#13]
* Mettre un `s` majuscule -> `Skript`
* Changer `tutoriaux` en `tutoriels`
![firefox_2019-01-16_19-15-53](https://user-images.githubusercontent.com/30158363/51269680-66787c00-19c3-11e9-8295-b5dc276cbe17.png)

* Mettre un `d` majuscule -> `Discord`
![firefox_2019-01-16_19-15-25](https://user-images.githubusercontent.com/30158363/51269681-66787c00-19c3-11e9-8922-8913fda8a23d.png)

* Enlever un `n` -> `panique`
![firefox_2019-01-16_19-14-26](https://user-images.githubusercontent.com/30158363/51269682-66787c00-19c3-11e9-8a6b-1b328251a938.png)

* Mettre un `s` majuscule -> `Skript` 
* Mettre le mot "api" en majuscule -> `API`
![image](https://user-images.githubusercontent.com/30158363/51269758-97f14780-19c3-11e9-84c7-17b3cda38783.png)

* Mettre un `s` majuscule -> `Skript` 
* Changer un `t` en `s` dans `extentions` ->  `extensions`
![image](https://user-images.githubusercontent.com/30158363/51269822-bce5ba80-19c3-11e9-981e-c7b962fb13b3.png)

* Enlever un `s` -> `détail` 
* Ajouter un `n` à "fonctionalités` -> `fonctionnalités`
![image](https://user-images.githubusercontent.com/30158363/51269911-e6064b00-19c3-11e9-85b9-a0ed8521e25e.png)

**Comment by Uneo7** [comment]
Je sais pas ou tu as vu un "tutoriaux" :p

**Comment by Angel-0** [comment]
Joke ? 
![image](https://user-images.githubusercontent.com/30158363/51277177-23c09f00-19d7-11e9-8844-00a28ec6c4da.png)

**Comment by Uneo7** [comment]
Haa mais y'a une majuscule c'est pour ça que la recherche donnais rien :)

**Comment by Uneo7** [comment]
Tout devrais être ok @Angel-0 .

**Comment by Angel-0** [comment]
Nope, t'as oublié de mettre un "api" en uppercase
![image](https://user-images.githubusercontent.com/30158363/51277475-12c45d80-19d8-11e9-9bcc-049648a7ece6.png)

**Comment by Uneo7** [comment]
Changé !

**Comment by Angel-0** [comment]
Plus aucune faute sur la homepage, je close
