### ISSUE TITLE
Editeur enlève les retours à la ligne

### ISSUE THREAD

**Issue by Angel-0** [Uneo7/Skript-MC-Doc#14]
L'éditeur, quand il charge enlève les retours à la ligne des patterns. A voir si ça peut être fixé (ça devrait l'être, car si on save sans refaire les nouvelles lignes, ça enregistre le texte comme une ligne)

**Comment by Angel-0** [comment]
Ca a été fixé avec le nouvel éditeur

**Comment by Uneo7** [comment]
Faut les remettre.
