### ISSUE TITLE
Mauvaise redirection

### ISSUE THREAD

**Issue by Angel-0** [Uneo7/Skript-MC-Doc#17]
Quand on save un article (édité ou pas), on est renvoyé à cette page https://doc.skript-mc.fr/documentation/article/?id=xxx où xxx = n° de l'article édité.
Cela pose problème, car ça supprime les filtres qu'on a préalablement utilisé, et nous oblige à le refaire.
Niveau pratique, c'est pas top du tout

**Comment by Uneo7** [comment]
Should be ok.
