### ISSUE TITLE
Ajouter un remplacement de syntaxe déprécier

### ISSUE THREAD

**Issue by noftaly** [Uneo7/Skript-MC-Doc#19]
Ajouter un champ facultatif pour mettre le lien d'une syntaxe à utiliser si celle de l'article que l'on écrit est dépréciée.

Si on en entre pas, alors l'infobox reste telle quelle, sinon il y a marqué en plus "Utilisez plutôt **cette** syntaxe"

**Comment by Uneo7** [comment]
Pas con

**Comment by Uneo7** [comment]
Fait.
